name : Deploying todo app

on:
    push:
        branches : [main]
        
jobs:
    build_docker_image:
        runs-on: ubuntu-latest
        name: build the docker image

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Docker login
              uses: docker/login-action@v2
              with:
                username: ${{secrets.DOCKERHUB_USERNAME}}
                password: ${{secrets.DOCKERHUB_TOKEN}}

            - name: Build and push
              uses: docker/build-push-action@v4
              with:
                context: .
                file: ./docker/Dockerfile.backend
                push: true
                tags: ayushsah0610/todo-app-backend:${{github.sha}}
            
            - name: Deploy to the VM
              run: |
                echo "${{ secrets.SSH_PRIVATE_KEY }}" &> ~/ssh_key
                chmod 700 /home/runner/ssh_key
                ssh -o StrictHostKeyChecking=no -i ~/ssh_key ec2-user@ec2-3-110-165-12.ap-south-1.compute.amazonaws.com -t "docker kill user_backend && docker run --name user_backend -d -p 8080:8080 ayushsah0610/todo-app-backend:${{github.sha}} "
            