name: Deploying Todo frontend
on:
    push:
        branches: [main]

jobs:
    build_docker_image:
        runs-on: ubuntu-latest
        name: build the docker image

        steps:
            - name: Checkout repository
              uses: actions/checkout@v3

            - name: Docker login
              uses: docker/login-action@v2
              with:
                username: ${{secrets.DOCKERHUB_USERNAME}}
                password: ${{secrets.DOCKERHUB_TOKEN}}

            - name: Docker push
              uses: docker/build-push-action@v4
              with: 
                context: .
                build-args: |
                    - DATABASE_URL: ${{secrets.DATABASE_URL}}
                file: docker/Dockerfile.frontend
                push: true
                tags: ayushsah0610/todo-frontend${{github.sha}}