name: Deploying ws backend
on:
    push:
        branches: [main]

jobs:
    build_docker_image:
        runs-on: ubuntu@latest
        name: build the docker image

        steps:
            - name: checkout repository
              uses: actions/checkout@v3

            - name: Docker login
              uses: docker/login-action@v2
              with:
                username: ${{secrets.DOCKERHUB_USERNAME}}
                password: ${{secrets.DOCKERHUB_TOKEN}}

            - name: build and push
              uses: docker/build-push-action@v4
              with: 
                context: .
                file: ./docker/Dockerfile.ws
                push: true
                tags: ayushsah0610/todo-app-ws:${{github.sha}}

